### ISSUE TITLE
I want to render a ply file on my phone, what do I need to do?

### ISSUE THREAD

**Issue by chunkitlau** [DirkToewe/sjmply#5]
I find code " Desktop.getDesktop().browse( tmp.toUri() ); " in PLY_Plotly.java, and it seems not working well in android because I can't import java.awt.Desktop. It seems it is a desktop lib and can't run in android. What can I do? Thanks in advance.

**Comment by DirkToewe** [comment]
Instead of using `PLY_Plotly.Mesh3d_show(title, ply)`, You could try `PLY_Plotly.Mesh3d_save(title, ply, filepath)` instead. You can then use some Android API call to open the generated `.html` file. If You look at the implementation of [PLY_Plotly.Mesh3d_show()](https://github.com/DirkToewe/sjmply/blob/master/src/main/java/org/jengineering/sjmply/PLY_Plotly.java#L249-L255), You can see that there is not much more to it.

I should add: [Plotly](https://github.com/plotly/plotly.js) is in my opinion not well optimized for smartphones.

**Comment by chunkitlau** [comment]
Thanks, but I want to render to image directly.
